services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - rede-nest

  api-nest:
    container_name: api-nest
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 3001:3000
    networks:
      - rede-nest
    depends_on:
      - mysql

networks:
  rede-nest:
    driver: bridge

volumes:
  db: