name: CI

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalando dependências
      working-directory: ./api
      run: |
        yarn
        yarn run test

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        working_directory: ./api
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Generate tag
      # Como esse step tem um output, cria um id para ser facilmente referenciado nos próximos steps
      id: generate_tag
      run: | 
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_LOGIN_ROLE }}

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build && push docker image
      id: build-docker-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      run: |
        docker build -t $REGISTRY/mateus-ci:$TAG -f prod.Dockerfile .
        docker tag $REGISTRY/mateus-ci:$TAG $REGISTRY/mateus-ci:latest
        docker push --all-tags $REGISTRY/mateus-ci
        IMAGE=$(echo $REGISTRY/mateus-ci:$TAG)
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Deploy to App Runner
      uses: awslabs/amazon-app-runner-deploy@main
      with:
        service: ${{ vars.SERVICE_NAME }}
        image: ${{ steps.build-docker-image.outputs.image }}
        access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 1
        momory: 2
        port: 3000