name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalando dependências
      working-directory: ./api
      run: |
        yarn
        yarn run test

    - name: Generate tag
      # Como esse step tem um output, cria um id para ser facilmente referenciado nos próximos steps
      id: generate_tag
      run: | 
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials for China region audience
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        audience: sts.amazonaws.com.cn
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::476422658806:role/ecr-role

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # - name: Login into the container registry
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: mateusfm/mateus-ci-nest:${{ steps.generate_tag.outputs.sha }}, mateusfm/mateus-ci-nest:latest