name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalando dependências
      working-directory: ./api
      run: |
        yarn
        yarn run test

    - name: Build docker image
      run: docker build -t mateus-ci-nest:latest .
